version: '3.3'

services:
  es:
    image: elasticsearch:6.5.4
    restart: always
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"

  logstash:
    image: logstash:6.5.4
    restart: always
    labels:
      com.example.service: "logstash"
      com.example.description: "For logging data"
    volumes:
      - ./tools/templates/logstash.template.conf:/logstash_dir/logstash.conf
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - es
    ports:
      - "5959:5959"

  kibana:
    image: kibana:6.5.4
    restart: always
    labels:
      com.example.service: "kibana"
      com.example.description: "Data visualisation and for log aggregation"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es

volumes:
  esdata: