node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"

    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-cicd"
    registryHost = "127.0.0.1:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.IMAGE_TAG="${tag}"

    stage "Build"

        sh "docker build -t ${imageName} -f tools/applications/${appName}/Dockerfile tools/applications/${appName}"

    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"

        kubernetesDeploy configs: "tools/deployment/k8s/${appName}/*.yaml", kubeconfigId: 'app_kubeconfig'
}
